/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogCategoryIndexRouteImport } from './routes/catalog/$category/index'
import { Route as CatalogCategoryProductRouteImport } from './routes/catalog/$category/$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoryIndexRoute = CatalogCategoryIndexRouteImport.update({
  id: '/catalog/$category/',
  path: '/catalog/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoryProductRoute = CatalogCategoryProductRouteImport.update({
  id: '/catalog/$category/$product',
  path: '/catalog/$category/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/$category/$product': typeof CatalogCategoryProductRoute
  '/catalog/$category/': typeof CatalogCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$category/$product': typeof CatalogCategoryProductRoute
  '/catalog/$category': typeof CatalogCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/$category/$product': typeof CatalogCategoryProductRoute
  '/catalog/$category/': typeof CatalogCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/catalog/'
    | '/catalog/$category/$product'
    | '/catalog/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/catalog'
    | '/catalog/$category/$product'
    | '/catalog/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/catalog/'
    | '/catalog/$category/$product'
    | '/catalog/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogCategoryProductRoute: typeof CatalogCategoryProductRoute
  CatalogCategoryIndexRoute: typeof CatalogCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$category/': {
      id: '/catalog/$category/'
      path: '/catalog/$category'
      fullPath: '/catalog/$category/'
      preLoaderRoute: typeof CatalogCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$category/$product': {
      id: '/catalog/$category/$product'
      path: '/catalog/$category/$product'
      fullPath: '/catalog/$category/$product'
      preLoaderRoute: typeof CatalogCategoryProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogCategoryProductRoute: CatalogCategoryProductRoute,
  CatalogCategoryIndexRoute: CatalogCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
